### Create New user
POST {{base_url}}/users
Content-Type: application/json

{
  "Email": "msyt1aabaaa969a@gmail.com",
  "Password": "woowoowoo",
  "Admin": true
}

### List all Users
GET {{base_url}}/users?pageSize=123&pageNumber=1